language: python
dist: xenial
install:
  - sudo apt-get install hfst
  - pipenv install --dev --skip-lock
script: 'pytest --cov=hfstol'
after_success: codecov
stages:
- test
- deploy
jobs:
  include:
  - python: '3.7'
  - python: '3.6'
  - python: '3.5'
